### ISSUE TITLE
Don't include color codes in buffer

### ISSUE THREAD

**Issue by nriley** [nschum/full-ack#11]
When I try to copy filenames from the results buffer, the color codes are at least partially still there, so I end up with lines such as:

```
[0m
[1;33m
```

Since (I think) these are all replaced by overlays, could the raw codes be removed?

**Comment by nschum** [comment]
You're right. I didn't think of that.

Unfortunately full-ack currently uses font-lock, so removing the codes requires somewhat of a rewrite...

**Comment by nriley** [comment]
Yeah, I eventually discovered that.  Someday, I guess...

**Comment by nschum** [comment]
Well, apparently it wasn't that hard... Please check out https://github.com/nschum/full-ack/tree/experimental

Maybe it didn't break anything. ;)

**Comment by nriley** [comment]
Thanks!

The only problem I'm noticing is when I use C-x ` to go through search results, the point in the file (as opposed to the full-ack buffer) is ending up at the end of the previous line rather than at the place where ack matched.  For example:

![Example](http://sabi.net/temp/full-ack.png)

**Comment by nschum** [comment]
OK. Please try again. :)

**Comment by nriley** [comment]
Much better, thanks!
