### ISSUE TITLE
problems with aquamacs

### ISSUE THREAD

**Issue by cognominal** [nschum/full-ack#7]
On Aquamacs 2.2, I get

With full-ack 2.1 :
  error in process filter: ack-visible-distance: Wrong type argument: number-or-marker-p, nil
  error in process filter: Wrong type argument: number-or-marker-p, nil
  finished with 0 matches

With full-ack 2.2 :

  error in process filter: if: Args out of range: 0, 0
  error in process filter: Args out of range: 0, 0
  Ack finished with 0 matches

**Comment by cognominal** [comment]
I meant respectively full-ack 0.2.1 and full-ack 0.2.2

**Comment by nschum** [comment]
I downloaded Aquamacs, but could not reproduce your problem.
Which version of ack are you using?
Do you have a custom ack configuration?
Does it happen with a fresh Aquamacs configuration?

Please customize "debug-on-error" to "always" in Aquamacs and try again. You should get a more detailed error message that you can post here.

**Comment by cognominal** [comment]
I don't know what was the problem. It works fine now. Thx for your help
